name: Build and Push Docker Image (Main)

on:
  push:
    paths:
      - apps/portal/**
      - packages/**
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version
        id: package-version
        run: |
          VERSION=$(node -p "require('./apps/portal/package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            hisptanzania/dhis2-public-portal:latest
            hisptanzania/dhis2-public-portal:${{ steps.package-version.outputs.VERSION }}
          build-args: |
            CONTEXT_PATH: null
          cache-from: type=gha
          cache-to: type=gha,mode=max
