name: Deploy Manager App to Development

env:
  DHIS2_BASE_URL: ${{ vars.DHIS2_BASE_URL }}
  D2_USERNAME: ${{ secrets.D2_USERNAME }}
  D2_PASSWORD: ${{ secrets.D2_PASSWORD }}

# Controls when the action will run
on:
  # Triggers the workflow on push events to the develop branch
  push:
    branches: [ develop ]
    paths:
      - 'apps/manager/**'
      - 'packages/shared/**'
      - 'packages/ui/**'
      - 'package.json'
      - 'yarn.lock'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # Wait for test to succeed before deploying
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Sets up a Node.js environment, with yarn as the package manager
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - name: Build Manager App
        run: yarn manager build

      # Deploy to development DHIS2 instance
      - name: Deploy to Development DHIS2 Instance
        run: yarn manager deploy --username ${{ env.D2_USERNAME }} ${{env.DHIS2_BASE_URL}}
